ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "model" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "serialNo" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "warranty" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "colour" TEXT;
