import { HttpException, HttpStatus } from '@nestjs/common';

export const ATTENDANCE_ERROR = {
  ATTENDANCE_DISABLED: 'ATTENDANCE_DISABLED',
  OUTSIDE_GEOFENCE: 'OUTSIDE_GEOFENCE',
  GPS_ACCURACY_TOO_LOW: 'GPS_ACCURACY_TOO_LOW',
  GPS_REQUIRED: 'GPS_REQUIRED',
  DEVICE_NOT_REGISTERED: 'DEVICE_NOT_REGISTERED',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  DEVICE_ALREADY_REGISTERED: 'DEVICE_ALREADY_REGISTERED',
  BIOMETRIC_REQUIRED: 'BIOMETRIC_REQUIRED',
  BIOMETRIC_MISMATCH: 'BIOMETRIC_MISMATCH',
  CHALLENGE_INVALID: 'CHALLENGE_INVALID',
  ALREADY_CHECKED_IN: 'ALREADY_CHECKED_IN',
  NOT_CHECKED_IN: 'NOT_CHECKED_IN',
  ALREADY_CHECKED_OUT: 'ALREADY_CHECKED_OUT',
  NO_SHIFT_ASSIGNED: 'NO_SHIFT_ASSIGNED',
  ATTENDANCE_NOT_ALLOWED: 'ATTENDANCE_NOT_ALLOWED',
  SETTINGS_INCOMPLETE: 'SETTINGS_INCOMPLETE',
  ON_LEAVE: 'ON_LEAVE',
  CLINIC_HOLIDAY: 'CLINIC_HOLIDAY',
  LEAVE_INVALID: 'LEAVE_INVALID',
} as const;

export class AttendanceException extends HttpException {
  constructor(code: string, message: string, status: HttpStatus = HttpStatus.BAD_REQUEST) {
    super({ success: false, error: { code, message } }, status);
  }
}
